KubeVersion: 1.33.0
Sources:
  gatekeeper:
    Namespace: gatekeeper
    ArgoSyncWave: 1
    Repository: https://open-policy-agent.github.io/gatekeeper/charts
    Chart: gatekeeper
    Version: 3.21.1
  fhir:
    Namespace: fhir
    ArgoSyncWave: 1
    Repository: oci://europe-docker.pkg.dev/prc-registry-180d/charts
    Chart: fhir
    Version: v1.0.3
